sudo: require
language: cpp
compiler: clang

before_install:
    # C++14
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    # Codecov
    - sudo pip install codecov

script:
    # Codecov
    - codecov

after_success:
    # Codecov
    - bash <(curl -s https://codecov.io/bash)
